datas <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", stringsAsFactors = FALSE)
subdata <- subset(datas, Date %in% c("1/2/2007","2/2/2007"))
dt <- strptime(paste(subdata$Date, subdata$Time, sep = " "), format = "%d/%m/%Y %H:%M:%S")
sm1 <- as.numeric(subdata$Sub_metering_1)
sm2 <- as.numeric(subdata$Sub_metering_2)
sm3 <- as.numeric(subdata$Sub_metering_3)
png("plot3.png", height = 480, width = 480)
plot(dt, sm1, col="black", type = "l",ylab="Energy Submetering", xlab="")
lines(dt, sm2,col= "red", type = "l")
lines(dt, sm3,col= "blue", type = "l")
dev.off()
