datas <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", stringsAsFactors = FALSE)
subdata <- subset(datas, Date %in% c("1/2/2007","2/2/2007"))
datetime <- strptime(paste(subdata$Date, subdata$Time, sep = " "), format = "%d/%m/%Y %H:%M:%S")
voltage <- as.numeric(subdata$Voltage)
grp <- as.numeric(subdata$Global_reactive_power)
sm1 <- as.numeric(subdata$Sub_metering_1)
sm2 <- as.numeric(subdata$Sub_metering_2)
sm3 <- as.numeric(subdata$Sub_metering_3)
gap <- as.numeric(subdata$Global_active_power)
png("plot4.png", height = 480, width = 480)
par(mfrow = c(2,2))
plot(datetime, gap, type = "l", xlab = "", ylab = "Global Active Power")
plot(datetime, voltage, type = "l", xlab = "datetime", ylab = "Voltage")
plot(datetime, sm1, type = "l", xlab = "", ylab = "Energy sub metering")
lines(datetime, sm2, type = "l", col="red")
lines(datetime, sm3, type = "l", col="blue")
legend("topright",legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black","red","blue"), lty = 1, lwd = 2)
plot(datetime, grp, type = "l", xlab = "datetime", ylab = "Global_reactive_power")
dev.off()
